Revert "mobicore: Remove dependency on deprecated stlport sources"
* TO FIX compile
hardware/samsung_slsi-cm/exynos5260/mobicore/daemon/ClientLib/ClientLib.cpp:43:16: fatal error: list: No such file or directory
 #include <list>
                ^
compilation terminated.
hardware/samsung_slsi-cm/exynos5260/mobicore/daemon/ClientLib/Session.cpp:34:18: fatal error: vector: No such file or directory
 #include <vector>
                  ^
compilation terminated.
make: *** [/home/haha/android/roms/n3n/cm-12.1/out/target/product/hl3g/obj/SHARED_LIBRARIES/libMcClient_intermediates/ClientLib/Device.o] Error 1
make: *** Waiting for unfinished jobs....

This reverts commit 4c2b370164014dd88947b690c85cf04877e919cd.